import {Theme} from "../global"

export const theme: Theme = {
    "--root": "white",
    "--base-card": "white",
    "--base-card-hover": "#f3f3f3",
    "--base-card-timestamp": "#8D8D8D",
    "--base-card-title": "rgba(0, 0, 0, 0.9)",
    "--base-card-message": "#909090",
    "--base-card-message-background": "#f6f6f6",
    "--base-card-unread": "#e2f0fd",
    "--base-card-border": "rgba(0, 0, 0, 0.1)",
    "--boolean-base-card": "#f4f4f48c",
    "--joblist-edit-base-card": "#ffffff",

    "--conversation-card-badge": "white",
    "--conversation-card-background": "rgb(10, 102, 194)",

    "--details-back": "rgba(106, 106, 106, 0.6)",
    "--details-reply-background": "white",
    "--details-reply-background-hover": "#e2f0fd",
    "--details-reply": "rgb(10, 102, 194)",
    "--details-reply-border": "rgb(10, 102, 194)",

    "--invitation-card-subtitle": "rgba(0, 0, 0, 0.6)",
    "--invitation-card-action-1": "#585858",
    "--invitation-card-action-2": "rgb(10, 102, 194)",
    "--invitation-card-custom-message-border": "#ebebeb",

    "--notification-card-action-1": "rgb(10, 102, 194)",
    "--notification-card-action-1-border": "rgb(10, 102, 194)",

    "--premium-message-background": "rgb(10, 102, 194)",
    "--premium-message": "white",
    "--premium-share": "black",
    "--premium-share-background": "#fddc3d",

    "--sign-in": "rgb(10, 102, 194)",
    "--sign-in-border": "rgb(10, 102, 194)",
    "--sign-in-background": "white",

    "--tab": "white",
    "--tab-selected": "rgb(10, 102, 194)",
    "--tab-border": "rgba(0, 0, 0, 0.1)",
    "--tab-item": "rgba(0, 0, 0)",
    "--tab-item-selected": "white",
    "--tab-badge": "white",
    "--tab-badge-background": "#ce3b28",

    "--header": "#585858",
    "--header-background": "white",

    "--loader": "rgb(10, 102, 194)",

    "--access-guard": "rgb(144, 144, 144)",

    "--auto-pill-on": "white",
    "--auto-pill-on-background": "rgb(10, 102, 194)",
    "--auto-pill-off": "white",
    "--auto-pill-off-background": "rgb(144, 144, 144)",

    "--complete-background": "rgb(10, 102, 194)",
    "--complete": "white",
    "--complete-progress-background": "rgba(10, 102, 194, 0.32)",
    "--complete-progress": "rgba(0, 0, 0, 0.3)",
    "--complete-disabled-background": "rgba(0, 0, 0, 0.08)",
    "--complete-disabled": "rgba(0, 0, 0, 0.3)",

    "--last-viewed-background": "rgba(88, 88, 88, 0.08)",
    "--last-viewed": "rgb(38,38,38)",

    "--salary-pill": "#117544",

    "--navbar-button": "#FFFFFF",

    "--note-card-border": "rgb(0 0 0 / 10%)",
    "--note-card-picture": "white",
    "--note-card-author": "black",
    "--note-card-text": "black",
    "--note-card-text-background": "rgba(244, 244, 244, 0.38)",

    "--notes-and-charts": "#909090",
    "--notes-and-charts-background": "#FFFFFF",
    "--notes-and-charts-shadow": "rgba(150, 163, 176, 0.27)",
    "--notes-and-charts-salary": "#585858",
    "--notes-background": "#FBFBFB",
    "--notes-input": "black",
    "--notes-input-background": "#FFFFFF",
    "--notes-input-border": "#E5E5E5",
    "--notes-input-outline": "rgb(10, 102, 194)",
    "--notes-input-submit": "rgb(10, 102, 194)",
    "--notes-input-submit-disabled": "rgb(144, 144, 144)",
    "--notes-counter-background": "rgba(144, 144, 144, 0.1)",
    "--notes-counter": "#585858",
    "--notes-color-1": "white",
    "--notes-color-2": "#D9D9D9",
    "--notes-color-3": "#0000009e",
    "--notes-color-4": "4A4A4A54",
    "--notes-color-5": "4A4A4A54",

    "--notes-container": "#909090",
    "--notes-container-background": "#FFFFFF",

    "--notes-manager-border": "#E0DFDC",
    "--notes-manager-header": "#FBFBFB",
    "--notes-manager-image": "white",
    "--notes-manager-name": "black",
    "--notes-manager-search": "rgba(217, 217, 217, 0.23)",
    "--notes-manager-search-dropdown": "#FFFFFF",
    "--notes-manager-search-dropdown-border": "rgba(88, 88, 88, 0.1)",
    "--notes-manager-search-dropdown-option": "white",
    "--notes-manager-search-dropdown-option-border": "#E0DFDC",

    "--pay-distribution-left": "#F4EACF",
    "--pay-distribution-middle": "#EAD5A5",
    "--pay-distribution-right": "#BCA878",

    "--stage": "white",
    "--stage-interested": "rgba(21, 105, 191, 0.74)",
    "--stage-interviewing": "rgba(240, 144, 0, 0.74)",
    "--stage-failed": "rgba(202, 26, 36, 0.74)",
    "--stage-hired": "rgba(17, 117, 68, 0.74)",
    "--stage-inactive": "rgb(144, 144, 144)",
    "--stage-passive": "#ECECEC",

    "--theme-switch": "white",
    "--theme-switch-border": "#E4E7EC",
    "--theme-switch-icon": "#FEBA5C",
    "--theme-switch-circle": "#FFECD1",
    "--theme-switch-circle-border": "#FEBA5C",

    "--pay-chart-color1": "#F3F2EF",
    "--pay-chart-color2": "#F4EDD8",
    "--pay-chart-border": "#A8A8A8",
    "--pay-chart-grid": "rgba(144, 144, 144, 0.2)",

    "--search-input": "white",
    "--reply-text-area-color": "white",
    "--reply-text-container-color": "#f9f9f9",
    "--reply-text-area-caret-color": "#000000",
    "--ln-dashboard-menu-icon-color": "rgb(102, 102, 102)",
    "--ln-dashboard-menu-icon-color-hover": "#000000",
    "--settings-icon-color": "#000000",

    "--navbar-button-text": "#383637",
    "--navbar-button-text-clicked": "#383637",
    "--boolean-search-query-container": "white",
    "--boolean-search-query-container-text": "#4A4A4A",
    "--joblist-table-color": "#FFFFFF",
    "--joblist-table-strip-color": "#FFFFFF",
    "--kanban-table-container-color": "#FFFFFF",
    "--kanban-table-more-color": "#727272",
    "--kanban-table-status-color": "#383637",
    "--kanban-table-list-card-color": "#585858",
    "--kanban-table-bottom-border-color": "#0000001c",
    "--kanban-table-message-color": "#585858",
    "--kanban-table-action-btn-color": "#585858",
    "--add-status-border": "#00000026",
    "--joblist-edit-input": "#bebebe42"
}
