name: Build App

on:
  push:
    paths:
      - 'app/**'
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 19.7 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: app/package-lock.json
      - name: Building and packaging
        run: |
          npm install
          npm run build-release
          npm pack
        working-directory: app
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: dist.zip
          path: dist_*.zip
